export enum OTPEnum {
  INITIAL_PHONE_VERIFICATION = 'INITIAL_PHONE_VERIFICATION',
  EDIT_PHONE_VERIFICATION = 'EDIT_PHONE_VERIFICATION',
  EMAIL_VERIFICATION = 'EDIT_EMAIL_VERIFICATION',
  PASSWORD_RESET = 'PASSWORD_RESET',
  TWO_FACTOR_AUTH = 'TWO_FACTOR_AUTH',
  ADD_CARD = 'ADD_CARD',
  DISABLE_CARD = 'DISABLE_CARD',
}
